backend:
  name: github
  repo: lpoulter/axiom-design-docs

media_folder: static/assets
public_folder: /assets

collections:
  - name: "component" # Used in routes, e.g., /admin/collections/blog
    label: "Component" # Used in the UI
    folder: "_posts/component" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{component-name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Component Name", name: "component_name", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "text"}
      - {label: "Section", name: "section", widget: "section-widget"}